### ISSUE TITLE
Allow tags

### ISSUE THREAD

**Issue by rauhs** [marianoguerra/transito#2]
Another one:

```
echo '[{[:user/by-id #om/id["xyz-blah"]] :foo}]'  | transito
```

**Comment by marianoguerra** [comment]
let me know if it works for you.

btw, I added an "edn to edn" (e2e) roundtrip to make it easier to check that the parser and writer understand the input correctly:

```
$ echo '[{[:user/by-id #om/id["xyz-blah"]] :foo}]'  | transito e2e -
[{[:user/by-id #om/id ["xyz-blah"]] :foo}]
```
